// ============================================
// EXPORT UTILITY SYSTEM
// Supports PDF, Excel, CSV, DOC formats
// ============================================

export interface ExportOptions {
  filename?: string;
  title?: string;
  headers?: string[];
}

export const ExportService = {
  // Convert data to CSV
  toCSV(data: any[], headers?: string[]): string {
    if (!data || data.length === 0) return '';
    
    const keys = headers || Object.keys(data[0]);
    const headerRow = keys.map(k => this.escapeCSV(k)).join(',');
    
    const rows = data.map(item => 
      keys.map(key => {
        const value = item[key];
        return this.escapeCSV(value === null || value === undefined ? '' : String(value));
      }).join(',')
    );
    
    return [headerRow, ...rows].join('\n');
  },

  escapeCSV(value: string): string {
    if (value.includes(',') || value.includes('"') || value.includes('\n')) {
      return `"${value.replace(/"/g, '""')}"`;
    }
    return value;
  },

  // Download CSV
  downloadCSV(data: any[], filename: string, headers?: string[]) {
    const csv = this.toCSV(data, headers);
    this.downloadFile(csv, `${filename}.csv`, 'text/csv;charset=utf-8;');
  },

  // Download Excel (XML format)
  downloadExcel(data: any[], filename: string, title: string = 'Report') {
    if (!data || data.length === 0) return;
    
    const headers = Object.keys(data[0]);
    
    let xml = '<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?>';
    xml += '<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">';
    xml += '<Worksheet ss:Name="' + title + '"><Table>';
    
    // Header row
    xml += '<Row>';
    headers.forEach(h => {
      xml += '<Cell><Data ss:Type="String">' + this.escapeXML(h) + '</Data></Cell>';
    });
    xml += '</Row>';
    
    // Data rows
    data.forEach(row => {
      xml += '<Row>';
      headers.forEach(h => {
        const value = row[h];
        const stringValue = value === null || value === undefined ? '' : String(value);
        xml += '<Cell><Data ss:Type="String">' + this.escapeXML(stringValue) + '</Data></Cell>';
      });
      xml += '</Row>';
    });
    
    xml += '</Table></Worksheet></Workbook>';
    
    this.downloadFile(xml, `${filename}.xls`, 'application/vnd.ms-excel');
  },

  // Download PDF (HTML format for printing)
  downloadPDF(data: any[], filename: string, title: string = 'Report') {
    if (!data || data.length === 0) return;
    
    const headers = Object.keys(data[0]);
    
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; }
    h1 { color: #1a1a1a; border-bottom: 2px solid #d4a574; padding-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { background: #d4a574; color: white; padding: 12px; text-align: left; }
    td { padding: 10px; border-bottom: 1px solid #ddd; }
    tr:nth-child(even) { background: #f9f9f9; }
    .footer { margin-top: 20px; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <table>
    <thead>
      <tr>
        ${headers.map(h => `<th>${this.escapeXML(h.replace(/_/g, ' '))}</th>`).join('')}
      </tr>
    </thead>
    <tbody>
      ${data.map(row => `
        <tr>
          ${headers.map(h => `<td>${this.escapeXML(String(row[h] || ''))}</td>`).join('')}
        </tr>
      `).join('')}
    </tbody>
  </table>
  <p class="footer">Generated by Saviman on ${new Date().toLocaleDateString()}</p>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

    this.downloadFile(html, `${filename}.pdf.html`, 'text/html');
  },

  // Download DOC (HTML format)
  downloadDOC(data: any[], filename: string, title: string = 'Report') {
    if (!data || data.length === 0) return;
    
    const headers = Object.keys(data[0]);
    
    const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: Arial; }
    h1 { color: #1a1a1a; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #d4a574; color: white; padding: 10px; text-align: left; }
    td { padding: 8px; border: 1px solid #ddd; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <table>
    <thead>
      <tr>
        ${headers.map(h => `<th>${this.escapeXML(h.replace(/_/g, ' '))}</th>`).join('')}
      </tr>
    </thead>
    <tbody>
      ${data.map(row => `
        <tr>
          ${headers.map(h => `<td>${this.escapeXML(String(row[h] || ''))}</td>`).join('')}
        </tr>
      `).join('')}
    </tbody>
  </table>
  <p style="font-size:12px;color:#666;">Generated by Saviman on ${new Date().toLocaleDateString()}</p></p>
</body>
</html>`;

    this.downloadFile(html, `${filename}.doc`, 'application/msword');
  },

  escapeXML(str: string): string {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  },

  downloadFile(content: string, filename: string, mimeType: string) {
    const blob = new Blob([content], { type: mimeType });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);
  },

  // Generic export function
  export(data: any[], filename: string, format: 'csv' | 'excel' | 'pdf' | 'doc', title?: string) {
    switch (format) {
      case 'csv':
        this.downloadCSV(data, filename);
        break;
      case 'excel':
        this.downloadExcel(data, filename, title);
        break;
      case 'pdf':
        this.downloadPDF(data, filename, title);
        break;
      case 'doc':
        this.downloadDOC(data, filename, title);
        break;
      default:
        this.downloadCSV(data, filename);
    }
  }
};

// ============================================
// SPECIFIC EXPORT HELPERS
// ============================================

export const exportLeads = (leads: any[], format: 'csv' | 'excel' | 'pdf' | 'doc') => {
  const data = leads.map(l => ({
    'Name': l.person_name,
    'Company': l.company_name,
    'Country': l.country_code,
    'Phone': l.contact_number,
    'Email': l.email,
    'Requirement': l.requirement_description,
    'Source': l.source,
    'Status': l.status,
    'Converted': l.converted ? 'Yes' : 'No',
    'Date': l.created_at ? new Date(l.created_at).toLocaleDateString() : ''
  }));
  ExportService.export(data, `leads_${new Date().toISOString().split('T')[0]}`, format, 'Leads Report');
};

export const exportInquiries = (inquiries: any[], format: 'csv' | 'excel' | 'pdf' | 'doc') => {
  const data = inquiries.map(i => ({
    'Name': i.name,
    'Company': i.company,
    'Email': i.email,
    'Phone': i.phone,
    'Product': i.product,
    'Message': i.message,
    'Status': i.status,
    'Priority': i.priority,
    'Date': i.created_at ? new Date(i.created_at).toLocaleDateString() : ''
  }));
  ExportService.export(data, `inquiries_${new Date().toISOString().split('T')[0]}`, format, 'Inquiries Report');
};

export const exportDonations = (donations: any[], format: 'csv' | 'excel' | 'pdf' | 'doc') => {
  const data = donations.map(d => ({
    'Donor': d.donor_name,
    'Email': d.donor_email,
    'Amount': d.amount,
    'Currency': d.currency || 'USD',
    'Method': d.payment_method,
    'Status': d.payment_status,
    'Transaction': d.transaction_id,
    'Date': d.created_at ? new Date(d.created_at).toLocaleDateString() : ''
  }));
  ExportService.export(data, `donations_${new Date().toISOString().split('T')[0]}`, format, 'Donations Report');
};

export const exportLogisticsQuotes = (quotes: any[], format: 'csv' | 'excel' | 'pdf' | 'doc') => {
  const data = quotes.map(q => ({
    'Name': q.user_name,
    'Email': q.email,
    'Country': q.country,
    'Address': q.delivery_address,
    'Weight': q.weight,
    'Product': q.product_name,
    'Cost': q.estimated_cost,
    'Partner': q.logistic_partner,
    'Status': q.status,
    'Date': q.created_at ? new Date(q.created_at).toLocaleDateString() : ''
  }));
  ExportService.export(data, `logistics_quotes_${new Date().toISOString().split('T')[0]}`, format, 'Logistics Quotes Report');
};

export default ExportService;
